# RECIPE-REPLICATION VARIANT g02_recipe — generated by make_recipe_replication.py
#
# Base candidate : runs/env_007/prompt_ladder/L2/cand_14/reward_v1.py
# Edits          : crate_dock_progress coefficient 6.0 -> 300.0 (x50); dense +20/step payoff on dock_state, added in BOTH branches
# Oracle-authored edit; see runs/env_007/REPAIR_TEST_FINDINGS.md.

_PREV_T = [-1.0]
_STREAK = [0]
_PAID = [False]
_ENTERED = [False]
_PREV_DIST = [1.0]


def compute_reward(obs, action, next_obs, original_reward, info, training_progress=0.0):
    # ---------- 回合边界检测 ----------
    t = float(next_obs[18])
    if t < _PREV_T[0] or t <= 1.0 / 400.0:
        _STREAK[0] = 0
        _PAID[0] = False
        _ENTERED[0] = False
        _PREV_DIST[0] = 1.0
    _PREV_T[0] = t

    # ---------- 几何量（泊位容差：|obs[12]|<=0.024, |obs[13]|<=0.030）----------
    dx = float(next_obs[12])
    dy = float(next_obs[13])
    dist = (dx * dx + dy * dy) ** 0.5

    inside = 1.0 if (abs(dx) <= 0.024 and abs(dy) <= 0.030) else 0.0

    # 货箱朝向误差（rad）
    ch = float(next_obs[10])
    sh = float(next_obs[11])
    ang_err = (sh * sh + (ch - 1.0) * (ch - 1.0)) ** 0.5
    if ang_err > 2.0:
        ang_err = 2.0
    align = 1.0 - ang_err / 0.5236
    if align < 0.0:
        align = 0.0

    # 货箱速度（m/s）
    cvx = float(next_obs[8]) * 3.0
    cvy = float(next_obs[9]) * 3.0
    crate_speed = (cvx * cvx + cvy * cvy) ** 0.5
    slow = 1.0 - crate_speed / 0.05
    if slow < 0.0:
        slow = 0.0

    dock_state = 1.0 if (inside > 0.5 and align > 0.0 and crate_speed < 0.05) else 0.0

    # ---------- 完成事件（连续 10 步）----------
    if dock_state > 0.5:
        _STREAK[0] += 1
    else:
        _STREAK[0] = 0

    success_event = 0.0
    if _STREAK[0] >= 10 and not _PAID[0]:
        _PAID[0] = True
        success_event = 300.0

    # 首次进入泊位（一次性）
    enter_event = 0.0
    if inside > 0.5 and not _ENTERED[0]:
        _ENTERED[0] = True
        enter_event = 30.0

    # ---------- 完成状态下：除一次性事件外其余组件必须为 0 ----------
    if dock_state > 0.5:
        components = {
            "crate_dock_progress": 0.0,
            "dock_quality_gate": 0.0,
            "gentleness": 0.0,
            "bounds_guard": 0.0,
            "success_event": success_event,
            "enter_event": enter_event,
        }
        components["REPAIR_settled_stream"] = float(20.0)
        total = success_event + enter_event + components["REPAIR_settled_stream"]
        return (float(total), components)

    # ---------- 过程型信号 ----------
    # 1) 增量接近信号（只在更接近时给分，门控对齐）
    progress = _PREV_DIST[0] - dist
    if progress < 0.0:
        progress = 0.0
    _PREV_DIST[0] = dist
    crate_dock_progress = 300.0 * progress * (0.3 + 0.7 * align)

    # 2) 联合条件软代理（仅在接近泊位时激活，作为门控乘增量，不单独按步给分）
    near_gate = 1.0 - dist / 0.15
    if near_gate < 0.0:
        near_gate = 0.0
    dock_quality_gate = 2.0 * near_gate * align * slow * progress

    # 3) 轻柔度：接触中且接近时惩罚
    crate_along_heading = cvx * float(obs[2]) + cvy * float(obs[3])
    closing = float(obs[4]) * 3.0 - crate_along_heading
    if closing < 0.0:
        closing = 0.0
    contact = 1.0 if float(next_obs[14]) > 0.5 else 0.0
    gentleness = -0.5 * contact * closing

    # 4) 越界守卫（小车 + 货箱）
    cx = float(next_obs[0])
    cy = float(next_obs[1])
    bounds_guard = 0.0
    for pos in (abs(cx), abs(cy)):
        if pos > 0.95:
            bounds_guard -= 40.0 * (pos - 0.95)
    crate_world_x = float(next_obs[6]) * 3.0 * float(obs[2]) - float(next_obs[7]) * 3.0 * float(obs[3]) + cx * 5.0
    crate_world_y = float(next_obs[6]) * 3.0 * float(obs[3]) + float(next_obs[7]) * 3.0 * float(obs[2]) + cy * 4.0
    for pos in (abs(crate_world_x) / 5.0, abs(crate_world_y) / 4.0):
        if pos > 0.95:
            bounds_guard -= 40.0 * (pos - 0.95)
    if bounds_guard < -60.0:
        bounds_guard = -60.0

    components = {
        "crate_dock_progress": crate_dock_progress,
        "dock_quality_gate": dock_quality_gate,
        "gentleness": gentleness,
        "bounds_guard": bounds_guard,
        "success_event": success_event,
        "enter_event": enter_event,
        "REPAIR_settled_stream": 0.0,   # dock_state is 0 in this branch
    }
    total = crate_dock_progress + dock_quality_gate + gentleness + bounds_guard + success_event + enter_event + components["REPAIR_settled_stream"]
    return (float(total), components)