"""Scale one term of a candidate, changing nothing else — a calibration test.

Hypothesis (from `runs/env_007/V8_PROMPT_PREREGISTRATION.md` and
`runs/env_007/CLOSE_SPEED_ISOLATION_FINDINGS.md` §3): `v8_cand_01` has the right reward
*shape* (bounded signed progress, a dominant per-step settled payoff, no switch-off) and still
does not settle (`max_stable` 2.42 steps vs 8.03 for the hand-written arm), because its
closing-speed ("gentleness") term is worth only -1.73 per episode whereas the hand-written
arm's equivalent term is what produces the 8-step hold. If that reading is right, scaling
*only* that coefficient up should move `max_stable` without touching anything else.

Usage:
    python make_calibration_variant.py --src REWARD.py --out-dir DIR --name v8c01_gentle_x10 \
        --anchor "-6.0 * contact * closing" --replace "-60.0 * contact * closing"
"""

from __future__ import annotations

import argparse
from pathlib import Path

HEADER = """# CALIBRATION VARIANT {name} — generated by make_calibration_variant.py
#
# Base  : {src}
# Edit  : {edit}
# Nothing else is changed: same structure, same gates, same other coefficients.
# Purpose and prediction: runs/env_007/CALIBRATION_TEST_PREREGISTRATION.md

"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--anchor", required=True, help="literal text to find (once)")
    ap.add_argument("--replace", required=True, help="literal replacement")
    args = ap.parse_args()

    src = Path(args.src)
    text = src.read_text(encoding="utf-8")
    n = text.count(args.anchor)
    if n != 1:
        raise SystemExit(f"anchor occurs {n} times (need exactly 1); refusing to patch blind")
    new = text.replace(args.anchor, args.replace, 1)

    out = Path(args.out_dir) / args.name
    out.mkdir(parents=True, exist_ok=True)
    (out / "reward_v1.py").write_text(
        HEADER.format(name=args.name, src=src.as_posix(),
                      edit=f"'{args.anchor}' -> '{args.replace}'") + new,
        encoding="utf-8")
    print(f"wrote {out / 'reward_v1.py'}")
    print(f"  edit: {args.anchor!r} -> {args.replace!r}")


if __name__ == "__main__":
    main()
