"""Ridge-width bisection: how narrow is the working band on the delta-progress coefficient?

Measured so far on the *same* fresh block (35000–35059), base = `r09_progress_x50_stream`:

    coefficient  600 (= x50, the recipe)        -> 16/60, dock 0.90   (arm o00_base)
    coefficient 2400 (= x200)                   ->  0/60, dock 0.72   (arm p02_progress_x200)

So the upper edge of the working band lies between x50 and x200. This script fills in the middle
with two arms, which is the cheapest way to put a number on "the ridge is narrow" — the quantity
`HANDOFF_QUESTIONS.md` P1–P5 identifies as the theoretical crux (an edit small enough to count as
localized, yet large enough that blind search misses it).

    q01_progress_x75    coefficient  900
    q02_progress_x100   coefficient 1200

Usage:
    python make_ridge_variants.py \
        --src runs/env_007/repair_test/r09_progress_x50_stream/reward_v1.py \
        --out-dir runs/env_007/ridge_width
"""

from __future__ import annotations

import argparse
from pathlib import Path

OLD = '    components["crate_to_dock_progress"] = 600.0 * progress * near_gate * gate\n'

VARIANTS = [
    dict(name="q01_progress_x75", coef=900.0, note="delta coefficient 600 -> 900 (x75)"),
    dict(name="q02_progress_x100", coef=1200.0, note="delta coefficient 600 -> 1200 (x100)"),
]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()

    src_text = Path(args.src).read_text(encoding="utf-8")
    if OLD not in src_text:
        raise SystemExit("progress anchor not found; refusing to patch blind")

    out = Path(args.out_dir)
    for v in VARIANTS:
        d = out / v["name"]
        d.mkdir(parents=True, exist_ok=True)
        new = f'    components["crate_to_dock_progress"] = {v["coef"]} * progress * near_gate * gate\n'
        header = (f"# RIDGE-WIDTH VARIANT {v['name']} — generated by make_ridge_variants.py\n"
                  f"#\n# Base reward : {args.src}\n# Edit        : {v['note']}\n"
                  f"# See runs/env_007/RIDGE_WIDTH_PREREGISTRATION.md\n\n")
        (d / "reward_v1.py").write_text(header + src_text.replace(OLD, new, 1), encoding="utf-8")
        print(f"  {v['name']:<20} {v['note']}")
    print(f"\nwrote {len(VARIANTS)} variants under {out}")


if __name__ == "__main__":
    main()
