"""Recipe replication on a SECOND LLM candidate: `L2/cand_14`.

The recipe, as measured on `L2/cand_00` (arm `r09`, 23/60 = 38.3 %, Fisher p = 8.7e-09 vs
0/60 — the first LLM-derived reward in this project ever to deliver the crate):

  (1) raise the candidate's **own approach term** by ~50x, so that acting beats doing
      nothing (measured: the advantage-scale probe `A` goes from −0.259 to +0.113); and
  (2) pay a **dense payoff on the instantaneous success predicate** (+20 per step while
      inside AND aligned AND slow), so that *settling* is profitable and not only
      approaching.

`L2/cand_14` is a natural replication target because it has the same skeleton: its own
approach term `crate_dock_progress = 6.0 * progress * (0.3 + 0.7 * align)`, an instantaneous
predicate `dock_state`, and one-off events (+300 success, +30 enter). It has one extra
feature that makes the second half of the recipe unavoidable and explicit: when
`dock_state > 0.5` it **returns early**, paying `success_event + enter_event` only — so while
the crate sits settled but before the 10-step hold completes, the reward is exactly **0**.
A stream that is only added to the non-docked branch would never fire, so it is added to
both branches.

Arms:
    g00_copy    byte-identical copy (machinery control; must reproduce 0/60)
    g01_stream  recipe (2) only: +20/step on `dock_state` in both branches
    g02_recipe  recipe (1) + (2): approach coefficient 6.0 -> 300.0, plus the stream

Usage:
    python make_recipe_replication.py \
        --src runs/env_007/prompt_ladder/L2/cand_14/reward_v1.py \
        --out-dir runs/env_007/recipe_replication
"""

from __future__ import annotations

import argparse
from pathlib import Path

PROGRESS_OLD = "    crate_dock_progress = 6.0 * progress * (0.3 + 0.7 * align)\n"
PROGRESS_NEW = "    crate_dock_progress = 300.0 * progress * (0.3 + 0.7 * align)\n"

EARLY_OLD = ("        total = success_event + enter_event\n"
             "        return (float(total), components)\n")
EARLY_NEW = ('        components["REPAIR_settled_stream"] = float(20.0)\n'
             "        total = success_event + enter_event + components[\"REPAIR_settled_stream\"]\n"
             "        return (float(total), components)\n")

FINAL_OLD = ('        "enter_event": enter_event,\n'
             "    }\n"
             "    total = crate_dock_progress + dock_quality_gate + gentleness "
             "+ bounds_guard + success_event + enter_event\n")
FINAL_NEW = ('        "enter_event": enter_event,\n'
             '        "REPAIR_settled_stream": 0.0,   # dock_state is 0 in this branch\n'
             "    }\n"
             "    total = crate_dock_progress + dock_quality_gate + gentleness "
             "+ bounds_guard + success_event + enter_event + components[\"REPAIR_settled_stream\"]\n")

VARIANTS = [
    dict(name="g00_copy", scale=False, stream=False,
         note="byte-identical copy: machinery control"),
    dict(name="g01_stream", scale=False, stream=True,
         note="recipe (2) only: dense +20/step payoff on the instantaneous predicate"),
    dict(name="g02_recipe", scale=True, stream=True,
         note="recipe (1)+(2): approach coefficient x50 AND the dense payoff"),
]


def build(src_text: str, v: dict, src: str) -> str:
    text = src_text
    edits = []

    if v["scale"]:
        if PROGRESS_OLD not in text:
            raise SystemExit("progress anchor not found; refusing to patch blind")
        text = text.replace(PROGRESS_OLD, PROGRESS_NEW, 1)
        edits.append("crate_dock_progress coefficient 6.0 -> 300.0 (x50)")

    if v["stream"]:
        if EARLY_OLD not in text or FINAL_OLD not in text:
            raise SystemExit("stream anchors not found; refusing to patch blind")
        text = text.replace(EARLY_OLD, EARLY_NEW, 1)
        text = text.replace(FINAL_OLD, FINAL_NEW, 1)
        edits.append("dense +20/step payoff on dock_state, added in BOTH branches")

    if not edits:
        edits.append("no change (copy control)")

    header = ("# RECIPE-REPLICATION VARIANT {name} — generated by make_recipe_replication.py\n"
              "#\n"
              "# Base candidate : {src}\n"
              "# Edits          : {edits}\n"
              "# Oracle-authored edit; see runs/env_007/REPAIR_TEST_FINDINGS.md.\n\n")
    return header.format(name=v["name"], src=src, edits="; ".join(edits)) + text


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()

    src_text = Path(args.src).read_text(encoding="utf-8")
    out = Path(args.out_dir)
    for v in VARIANTS:
        d = out / v["name"]
        d.mkdir(parents=True, exist_ok=True)
        (d / "reward_v1.py").write_text(build(src_text, v, args.src), encoding="utf-8")
        print(f"  {v['name']:<14} {v['note']}")
    print(f"\nwrote {len(VARIANTS)} variants under {out}")


if __name__ == "__main__":
    main()
