"""Build align-fix variants of `L0/cand_02`, the arm whose alignment term is inverted.

Root cause (verified against the environment source, not guessed)
----------------------------------------------------------------
`custom_envs/fragile_cargo_dock_env.py`:

    obs[10] = math.cos(cargo_angle)      # 10 crate heading cos  (ABSOLUTE crate angle)
    obs[11] = math.sin(cargo_angle)      # 11 crate heading sin
    DOCK_ANGLE = 0.0                     # rad, dock is axis aligned
    ANGLE_TOL  = math.radians(30.0)      # success needs |cargo_angle| < 30 deg

`L0/cand_02` writes

    heading_align = 1.0 - abs(cos_h)     # cos_h = obs[10]

which is **maximal at cargo_angle = +/-90 deg** — perpendicular to the dock, i.e. exactly
outside the success set — and zero when the crate is aligned. Its own comment ("|cos| near 0
means aligned, mod 180 deg can dock") shows the misconception: it treats an *absolute*
heading as if it were a heading *error*. The term carries 94 % of that arm's reward mass
(+311 per episode measured), so the policy is paid to hold a state that cannot succeed.

The other candidates get this right (`L2/cand_00` uses `1 - |obs[11]|`; probe D uses
`obs[10] >= cos(30 deg)`), which is why this is a *generation* error rather than an
environment quirk.

Independently, the training-free `trajectory_ranking_check.py` scored this arm **0.268**
(measured in the ladder run, before this code was read) — the only one of the eight below
0.5, i.e. it ranks success *below* failure. The fix should move it above 0.5.

Usage
-----
    python make_align_fix_variants.py \
        --src runs/env_007/prompt_ladder/L0/cand_02/reward_v1.py \
        --out-dir runs/env_007/align_fix_test
"""

from __future__ import annotations

import argparse
from pathlib import Path

ALIGN_OLD = "    heading_align = 1.0 - abs(cos_h)\n"
ALIGN_NEW = "    heading_align = 1.0 - abs(sin_h)\n"

SPEED_OLD = "    crate_speed = (crate_vx * crate_vx + crate_vy * crate_vy) ** 0.5\n"
SPEED_NEW = ("    # obs[8], obs[9] are crate velocity / SPEED_SCALE(=3.0); restore m/s so the\n"
             "    # speed penalties below are not 9x too weak\n"
             "    crate_speed = 3.0 * (crate_vx * crate_vx + crate_vy * crate_vy) ** 0.5\n")

TOTAL_OLD = "    total = r_progress + r_quality + r_speed_near + r_soft + r_bounds + r_action\n"

GENTLE_BLOCK = '''
    # ---- REPAIR: obs-only gentleness (probe D's decisive ingredient) ----
    _gcos_h, _gsin_h = obs[2], obs[3]
    _gcart_fwd = obs[4] * 3.0
    _gvx, _gvy = obs[8] * 3.0, obs[9] * 3.0
    _galong = _gvx * _gcos_h + _gvy * _gsin_h
    _gclosing = _gcart_fwd - _galong
    if _gclosing < 0.0:
        _gclosing = 0.0
    r_gentle = -0.05 * float(contact) * _gclosing
'''

VARIANTS = [
    dict(name="f00_copy", align=False, units=False, gentleness=False,
         note="exact copy of L0/cand_02: machinery control, must reproduce 0/60"),
    dict(name="f01_align_fix", align=True, units=False, gentleness=False,
         note="ONE subscript: heading_align 1-|obs[10]| -> 1-|obs[11]|, nothing else"),
    dict(name="f02_align_fix_units", align=True, units=True, gentleness=False,
         note="f01 + crate_speed restored to m/s (obs[8],[9] are /3.0)"),
    dict(name="f03_align_fix_gentle", align=True, units=False, gentleness=True,
         note="f01 + probe D's obs-only gentleness term"),
]


def build(src_text: str, variant: dict, src: str) -> str:
    text = src_text
    edits = []

    if variant["align"]:
        if ALIGN_OLD not in text:
            raise SystemExit("align anchor not found; refusing to patch blind")
        text = text.replace(ALIGN_OLD, ALIGN_NEW, 1)
        edits.append("heading_align: 1.0 - abs(cos_h) -> 1.0 - abs(sin_h)")

    if variant["units"]:
        if SPEED_OLD not in text:
            raise SystemExit("crate_speed anchor not found; refusing to patch blind")
        text = text.replace(SPEED_OLD, SPEED_NEW, 1)
        edits.append("crate_speed restored to m/s (x3.0)")

    if variant["gentleness"]:
        if TOTAL_OLD not in text:
            raise SystemExit("total anchor not found; refusing to patch blind")
        text = text.replace(TOTAL_OLD, GENTLE_BLOCK + "\n" + TOTAL_OLD, 1)
        text = text.replace(
            "    total = r_progress + r_quality + r_speed_near + r_soft + r_bounds + r_action\n",
            "    total = (r_progress + r_quality + r_speed_near + r_soft + r_bounds\n"
            "             + r_action + r_gentle)\n", 1)
        text = text.replace(
            '        "action_smoothness": float(r_action),\n',
            '        "action_smoothness": float(r_action),\n'
            '        "REPAIR_gentleness": float(r_gentle),\n', 1)
        edits.append("added obs-only gentleness (weight -0.05)")

    if not edits:
        edits.append("no change (copy control)")

    header = ("# ALIGN-FIX VARIANT {name} — generated by make_align_fix_variants.py\n"
              "#\n"
              "# Base candidate : {src}\n"
              "# Edits          : {edits}\n"
              "# Everything else is the candidate's own code, unmodified. Oracle-authored edit:\n"
              "# it measures whether this root cause explains the failure, NOT whether a search\n"
              "# would find the fix. See runs/env_007/ALIGN_FIX_PREREGISTRATION.md.\n\n")
    return header.format(name=variant["name"], src=src, edits="; ".join(edits)) + text


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()

    src_text = Path(args.src).read_text(encoding="utf-8")
    out_root = Path(args.out_dir)
    for v in VARIANTS:
        d = out_root / v["name"]
        d.mkdir(parents=True, exist_ok=True)
        (d / "reward_v1.py").write_text(build(src_text, v, args.src), encoding="utf-8")
        print(f"  {v['name']:<24} {v['note']}")
    print(f"\nwrote {len(VARIANTS)} variants under {out_root}")


if __name__ == "__main__":
    main()
