"""Overshoot-cliff ablation on the known-working reward: is "make overshoot very negative"
the right way to teach the release lead time?

The hypothesis under test (from the user's pushing-task experience, and consistent with this
repo's own `record_overshoot_diagnosis.py`: the CREATE policy "blows straight through" the dock
once the time limit is lifted, while the native-reward policy releases early and settles):

    the AI never learns the *release lead time*, so the fix is to make the score for pushing
    PAST the dock extremely low and let it find the near-but-not-past point.

Base reward: `runs/env_007/repair_test/r09_progress_x50_stream/reward_v1.py` — the measured
two-edit repair of `L2/cand_00` (23/60 = 38.3 %, dock 0.98). Patching the *working* reward is
what makes this a clean ablation: a baseline that already delivers can be improved or damaged
on one axis at a time, on the same fresh-seed block.

Geometry, verified against `custom_envs/fragile_cargo_dock_env.py`: the cart spawns at
x ∈ (−3.5, −2.8) and the crate at x ∈ (−1.9, −1.1), the dock is at `DOCK_X = 2.6`, so the push
direction is **+x** and `obs[12] = (cargo.x − DOCK_X)/5.0 > 0` means **past the dock centre**.
The dock's x tolerance is 0.024, so overshoot starts at `obs[12] > 0.024`.

Arms (all one 1.2M run, seed 0, same config; scored on fresh seeds 35000–35059):

    o00_base           byte-identical copy of r09 — matched baseline on the SAME block
    o01_overshoot      + hinge penalty on overshoot, weight −20 (the per-step clip ceiling)
    o02_gentle         + probe D's closing-speed gentleness (−0.05·contact·closing)
    o03_both           + overshoot hinge AND gentleness
    o04_overshoot_x10  + the same hinge at weight −200 (10x past the clip)

Usage:
    python make_overshoot_variants.py \
        --src runs/env_007/repair_test/r09_progress_x50_stream/reward_v1.py \
        --out-dir runs/env_007/overshoot_ablation
"""

from __future__ import annotations

import argparse
from pathlib import Path

TOTAL_ANCHOR = "    total = 0.0\n"

OVERSHOOT = '''
    # ---- OVERSHOOT: crate pushed past the far edge of the dock tolerance ----
    # obs[12] > 0 is beyond the dock centre along the (+x) push direction; tolerance 0.024.
    _ov = float(next_obs[12]) - 0.024
    if _ov < 0.0:
        _ov = 0.0
    if _ov > 0.04:
        _ov = 0.04
    components["OVERSHOOT_penalty"] = float({w} * (_ov / 0.04))
'''

GENTLENESS = '''
    # ---- GENTLENESS: closing speed while in contact (the release-lead-time signal) ----
    _gcos_h, _gsin_h = obs[2], obs[3]
    _gcart_fwd = obs[4] * 3.0
    _galong = crate_vx * _gcos_h + crate_vy * _gsin_h
    _gclosing = _gcart_fwd - _galong
    if _gclosing < 0.0:
        _gclosing = 0.0
    components["REPAIR_gentleness"] = float(-0.05 * contact * _gclosing)
'''

VARIANTS = [
    dict(name="o00_base", overshoot=None, gentleness=False,
         note="byte-identical copy of r09: matched baseline, expected ~23/60"),
    dict(name="o01_overshoot", overshoot=-20.0, gentleness=False,
         note="+ overshoot hinge at the clip ceiling (-20/step)"),
    dict(name="o02_gentle", overshoot=None, gentleness=True,
         note="+ probe D's closing-speed gentleness (the measured release-lead-time signal)"),
    dict(name="o03_both", overshoot=-20.0, gentleness=True,
         note="+ overshoot hinge AND gentleness"),
    dict(name="o04_overshoot_x10", overshoot=-200.0, gentleness=False,
         note="+ overshoot hinge at -200/step: 10x past the clip"),
]


def build(src_text: str, v: dict, src: str) -> str:
    text = src_text
    edits = []

    if v["overshoot"] is not None:
        if TOTAL_ANCHOR not in text:
            raise SystemExit("anchor 'total = 0.0' not found; refusing to patch blind")
        block = OVERSHOOT.format(w=v["overshoot"])
        text = text.replace(TOTAL_ANCHOR, block + "\n" + TOTAL_ANCHOR, 1)
        edits.append(f"overshoot hinge penalty, weight {v['overshoot']}")

    if v["gentleness"]:
        if TOTAL_ANCHOR not in text:
            raise SystemExit("anchor 'total = 0.0' not found; refusing to patch blind")
        text = text.replace(TOTAL_ANCHOR, GENTLENESS + "\n" + TOTAL_ANCHOR, 1)
        edits.append("closing-speed gentleness (-0.05 * contact * closing)")

    if not edits:
        edits.append("no change (copy control)")

    header = ("# OVERSHOOT-ABLATION VARIANT {name} — generated by make_overshoot_variants.py\n"
              "#\n"
              "# Base reward : {src}  (the measured two-edit repair, 23/60)\n"
              "# Edits       : {edits}\n"
              "# Oracle-authored ablation; see runs/env_007/OVERSHOOT_ABLATION_PREREGISTRATION.md\n\n")
    return header.format(name=v["name"], src=src, edits="; ".join(edits)) + text


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    ap.add_argument("--out-dir", required=True)
    args = ap.parse_args()

    src_text = Path(args.src).read_text(encoding="utf-8")
    out = Path(args.out_dir)
    for v in VARIANTS:
        d = out / v["name"]
        d.mkdir(parents=True, exist_ok=True)
        (d / "reward_v1.py").write_text(build(src_text, v, args.src), encoding="utf-8")
        print(f"  {v['name']:<18} {v['note']}")
    print(f"\nwrote {len(VARIANTS)} variants under {out}")


if __name__ == "__main__":
    main()
