# Generic commit-guarded training queue.
#
# The queue logic (and why it exists) is documented in
# runs/env_007/ladder_train/README.md: on this machine the binding constraint is the
# page file / commit limit, not RAM, and launching N trainings at once makes the
# SubprocVecEnv workers die during `import torch` (WinError 1455 / 页面文件太小) while the
# parent hangs at 0 CPU.
#
# This is the same hardware as ladder_train/launch_and_analyze.ps1, generalised so any
# follow-up experiment (Branch A selector pool, Branch B 0.6M rung) can reuse it.
#
# Usage
# -----
#   # 1. write a spec (generated by the caller, or by hand)
#   #    [{"name":"L2_cand_00_s0", "reward":"runs/env_007/prompt_ladder/L2/cand_00/reward_v1.py",
#   #      "save_dir":"runs/env_007/ladder_short/L2_cand_00_s0", "seed":0}, ...]
#   # 2. run the queue
#   & runs/env_007/train_queue.ps1 -Spec runs/env_007/ladder_short/spec.json -MaxParallel 4
#
# Spec fields per job: name (required), reward (required), save_dir (required),
# total_timesteps (default 1200000), seed (default 0), eval_episodes (default 20),
# config (default configs/env007_terminal_rule_pilot.yaml).

param(
  [Parameter(Mandatory = $true)][string]$Spec,
  [int]$MaxParallel = 4,
  [double]$MinFreeCommitGB = 3.0,
  [int]$HangSeconds = 300,
  [int]$MaxAttempts = 2,
  [int]$PollSeconds = 20,
  [int]$StaggerSeconds = 20,
  [string]$LogDir = "runs/env_007",
  [switch]$QueueOnly
)

$ErrorActionPreference = "Stop"
$Repo = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$Py = "D:\Code\python\research\llm_env_310\Scripts\python.exe"

if (-not (Test-Path (Join-Path $Repo $Spec))) { throw "spec not found: $Spec" }
$specJobs = Get-Content (Join-Path $Repo $Spec) -Raw | ConvertFrom-Json

function Get-FreeCommitGB {
  $os = Get-CimInstance Win32_OperatingSystem
  return [math]::Round($os.FreeVirtualMemory / 1MB, 2)
}

function Start-Candidate {
  param($Job)
  $saveDir = Join-Path $Repo $Job.save_dir
  $log = Join-Path $Repo "$LogDir/train_$($Job.name).log"
  $errLog = Join-Path $Repo "$LogDir/train_$($Job.name).err.log"
  New-Item -ItemType Directory -Force -Path $saveDir | Out-Null

  $argList = @(
    "-m", "training.train_sb3_wrapper",
    "--config", $Job.config,
    "--reward", $Job.reward,
    "--run-name", "train_$($Job.name)",
    "--save-dir", $Job.save_dir,
    "--total-timesteps", "$($Job.total_timesteps)",
    "--eval-episodes", "$($Job.eval_episodes)",
    "--seed", "$($Job.seed)"
  )
  $env:OMP_NUM_THREADS = "6"
  $env:MKL_NUM_THREADS = "6"
  $p = Start-Process -FilePath $Py -ArgumentList $argList -WorkingDirectory $Repo `
    -RedirectStandardOutput $log -RedirectStandardError $errLog -WindowStyle Hidden -PassThru
  Start-Sleep -Seconds $StaggerSeconds

  $realPid = $null
  for ($i = 0; $i -lt 15; $i++) {
    $child = Get-CimInstance Win32_Process -Filter "ParentProcessId=$($p.Id)" -ErrorAction SilentlyContinue |
      Where-Object { $_.Name -eq "python.exe" } | Select-Object -First 1
    if ($child) { $realPid = $child.ProcessId; break }
    Start-Sleep -Seconds 2
  }
  $Job.ShimPid = $p.Id
  $Job.RealPid = $realPid
  $Job.Attempts++
  $Job.LastCpu = 0.0
  $Job.CpuChangedAt = Get-Date
  Write-Host ("[start ] {0,-24} attempt {1} real={2} steps={3} seed={4} commit_free={5}GB" -f `
    $Job.name, $Job.Attempts, $realPid, $Job.total_timesteps, $Job.seed, (Get-FreeCommitGB))
}

$jobs = @()
foreach ($j in $specJobs) {
  $jobs += [pscustomobject]@{
    name = $j.name
    reward = $j.reward
    save_dir = $j.save_dir
    total_timesteps = if ($null -ne $j.total_timesteps) { $j.total_timesteps } else { 1200000 }
    seed = if ($null -ne $j.seed) { $j.seed } else { 0 }
    eval_episodes = if ($null -ne $j.eval_episodes) { $j.eval_episodes } else { 20 }
    config = if ($j.config) { $j.config } else { "configs/env007_terminal_rule_pilot.yaml" }
    Attempts = 0; ShimPid = $null; RealPid = $null
    LastCpu = 0.0; CpuChangedAt = Get-Date
    Done = $false; Failed = $false
  }
}

Write-Host "spec  : $Spec"
Write-Host "queue : $($jobs.Count) jobs, max $MaxParallel parallel"
Write-Host "commit guard: start only if free commit > $MinFreeCommitGB GB (now $(Get-FreeCommitGB) GB)"
Write-Host ""

while ($true) {
  foreach ($j in @($jobs | Where-Object { -not $_.Done -and -not $_.Failed -and $_.RealPid })) {
    $dir = Join-Path $Repo $j.save_dir
    if (Test-Path (Join-Path $dir "training_summary.json")) {
      $j.Done = $true
      Write-Host ("[done  ] {0}" -f $j.name)
      continue
    }
    $pr = Get-Process -Id $j.RealPid -ErrorAction SilentlyContinue
    if (-not $pr) {
      Write-Host ("[died  ] {0} (no summary)" -f $j.name)
      $j.RealPid = $null
      if ($j.Attempts -ge $MaxAttempts) { $j.Failed = $true } else { Write-Host ("[retry ] {0}" -f $j.name) }
      continue
    }
    if ($pr.CPU -gt $j.LastCpu + 1.0) {
      $j.LastCpu = $pr.CPU
      $j.CpuChangedAt = Get-Date
    } elseif (((Get-Date) - $j.CpuChangedAt).TotalSeconds -gt $HangSeconds) {
      Write-Host ("[hung  ] {0} no CPU progress for ${HangSeconds}s -> kill+retry" -f $j.name)
      Stop-Process -Id $j.RealPid -Force -ErrorAction SilentlyContinue
      if ($j.ShimPid) { Stop-Process -Id $j.ShimPid -Force -ErrorAction SilentlyContinue }
      $j.RealPid = $null
      Remove-Item (Join-Path $dir "monitor") -Recurse -Force -ErrorAction SilentlyContinue
      if ($j.Attempts -ge $MaxAttempts) { $j.Failed = $true }
    }
  }

  $doneCount = @($jobs | Where-Object { $_.Done }).Count
  $failedCount = @($jobs | Where-Object { $_.Failed }).Count
  $running = @($jobs | Where-Object { -not $_.Done -and -not $_.Failed -and $_.RealPid })
  $pending = @($jobs | Where-Object { -not $_.Done -and -not $_.Failed -and -not $_.RealPid })
  Write-Host ("[{0}] done {1}/{2} failed {3} running {4} pending {5} commit_free {6}GB" -f `
    (Get-Date).ToString("HH:mm:ss"), $doneCount, $jobs.Count, $failedCount,
    $running.Count, $pending.Count, (Get-FreeCommitGB))

  if ($doneCount + $failedCount -eq $jobs.Count) { break }

  if ($pending.Count -gt 0 -and $running.Count -lt $MaxParallel) {
    if ((Get-FreeCommitGB) -lt $MinFreeCommitGB) {
      Write-Host ("        waiting for commit headroom (need > $MinFreeCommitGB GB)")
    } else {
      Start-Candidate -Job $pending[0]
      continue
    }
  }

  Start-Sleep -Seconds $PollSeconds
}

Write-Host ""
$failed = @()
foreach ($j in $jobs) {
  $ok = Test-Path (Join-Path $Repo "$($j.save_dir)/training_summary.json")
  if (-not $ok) { $failed += $j.name }
  Write-Host ("[result] {0,-24} summary={1} attempts={2}" -f $j.name, $ok, $j.Attempts)
}
if ($failed.Count -gt 0) { Write-Warning "no summary for: $($failed -join ', ')" }
