"""Extract the v9 reward-structure block from prompts/eureka_01_initial_reward_v9.md
and materialise it as a standalone knowledge file for the CREATE pipeline.

Why this exists
---------------
v9's measured effect (4/60 -> 58/60) came from one thing: the generator was told the
*structure* of the environment's own reward (nine named terms with semantics and
weights). The EUREKA flow gets that text through `prompts/eureka_01_initial_reward_v9.md`.

The CREATE flow (`pipeline/run_iterative_experiment.py` -> `run_direct_generation_pipeline`)
does not use that prompt at all: it builds an `environment_card.md` from the task spec and
feeds `prompts/02_reward_generator_prompt.md`. To compare the two methods under the same
reward information, CREATE must receive the same structure.

Copy-pasting the table by hand would let the two texts drift apart, so this script extracts
the block *verbatim* from the v9 prompt and writes it next to the run artifacts. Re-run it
whenever the v9 prompt changes; the output is byte-identical apart from the file header.

Usage:
    python tools/extract_v9_structure_block.py
"""

from __future__ import annotations

import hashlib
from pathlib import Path

SRC = Path("prompts/eureka_01_initial_reward_v9.md")
DST = Path("runs/env_007/CREATE_V9_STRUCTURE.md")

START = "# 已知的奖励结构（本版本新增"
END = "\n# 设计方法\n"

# Terms the block is required to name; a silent drift must fail loudly here.
REQUIRED_TERMS = [
    "approach_cargo", "progress", "dock_enter", "roughness", "action_cost",
    "time_cost", "hard_hit", "terminal_success", "terminal_failure",
]

HEADER = """<!-- Generated by tools/extract_v9_structure_block.py — do not edit by hand.

     Provenance: the block below is extracted VERBATIM from
     `prompts/eureka_01_initial_reward_v9.md`, the prompt whose measured effect was
     4/60 -> 58/60 (runs/env_007/V9_STRUCTURE_FINDINGS.md). The CREATE pipeline injects it
     into the environment card so that CREATE and EUREKA receive the same reward
     information; see runs/env_007/CREATE_V9_SPEC_AND_STRUCTURE.md for the protocol and the
     declared asymmetry against the older CREATE baseline.

     Source sha256: {src_sha}
     Block sha256 : {block_sha}
-->

"""

FENCE_OPEN = "<!-- BEGIN v9 structure block (verbatim) -->\n\n"
FENCE_CLOSE = "\n<!-- END v9 structure block -->\n"


def main() -> None:
    text = SRC.read_text(encoding="utf-8")
    start = text.index(START)
    end = text.index(END, start)
    block = text[start:end].rstrip() + "\n"

    missing = [term for term in REQUIRED_TERMS if f"`{term}`" not in block]
    if missing:
        raise SystemExit(f"structure block is missing required terms: {missing}")
    if "优先级声明" not in block:
        raise SystemExit("structure block lost its precedence declaration")

    src_sha = hashlib.sha256(text.encode("utf-8")).hexdigest()
    block_sha = hashlib.sha256(block.encode("utf-8")).hexdigest()

    out = (
        HEADER.format(src_sha=src_sha, block_sha=block_sha)
        + FENCE_OPEN
        + block
        + FENCE_CLOSE
    )
    DST.write_text(out, encoding="utf-8")
    print(f"wrote {DST} ({len(out)} chars)")
    print(f"  source sha256: {src_sha}")
    print(f"  block  sha256: {block_sha}")
    print(f"  terms present: {len(REQUIRED_TERMS)}/{len(REQUIRED_TERMS)}")


if __name__ == "__main__":
    main()
