# APPROACH-ABLATION VARIANT p04_proximity_gentle — generated by make_approach_variants.py
#
# Base reward : runs/env_007/repair_test/r09_progress_x50_stream/reward_v1.py  (the measured two-edit repair, 23/60)
# Edits       : added APPROACH_proximity = 20/(1+30d); closing-speed gentleness (-0.05 * contact * closing)
# Oracle-authored ablation; see runs/env_007/APPROACH_ABLATION_PREREGISTRATION.md

# REPAIR VARIANT r09_progress_x50_stream — generated by make_repair_variants.py
#
# Base candidate : runs/env_007/prompt_ladder/L2/cand_00/reward_v1.py
# Edits          : crate_to_dock_progress coefficient 12.0 -> 600.0; added a dense +20/step payoff stream on the candidate's own done_cond
# Everything else (module state, gating, thresholds, remaining magnitudes) is the
# candidate's own code, unmodified. This is an oracle-authored edit: it bounds what
# a repair operator could reach, and is NOT evidence that a search would find it.
# See runs/env_007/REPAIR_TEST_PREREGISTRATION.md for the fixed predictions.

_PREV_T = [-1.0]
_STREAK = [0]
_PAID = [False]
_ENTERED = [False]


def compute_reward(obs, action, next_obs, original_reward, info, training_progress=0.0):
    # ---------- episode 边界检测 ----------
    t = float(next_obs[18])
    if t < _PREV_T[0] or t <= 1.0 / 400.0:
        _STREAK[0] = 0
        _PAID[0] = False
        _ENTERED[0] = False
    _PREV_T[0] = t

    # ---------- 几何量（全部来自已声明维度） ----------
    # 货箱到泊位的有符号偏移（已归一化）
    dx_now = obs[12]
    dy_now = obs[13]
    dx_nxt = next_obs[12]
    dy_nxt = next_obs[13]

    d_now = (dx_now * dx_now + dy_now * dy_now) ** 0.5
    d_nxt = (dx_nxt * dx_nxt + dy_nxt * dy_nxt) ** 0.5

    # 容差（环境事实给定）
    TOL_X = 0.024
    TOL_Y = 0.030
    inside = 1.0 if (abs(dx_nxt) <= TOL_X and abs(dy_nxt) <= TOL_Y) else 0.0

    # 货箱朝向误差（rad）
    c_cos = next_obs[10]
    c_sin = next_obs[11]
    crate_ang = 0.0
    if c_cos != 0.0 or c_sin != 0.0:
        crate_ang = (c_sin * c_sin + c_cos * c_cos) ** 0.5
    # 朝向误差：用 atan2 的粗代理（|sin| 越大越不对齐）
    align = 1.0 - abs(c_sin)          # 1 = 完全对齐, 0 = 90°
    if align < 0.0:
        align = 0.0
    if align > 1.0:
        align = 1.0

    # 货箱速度（m/s）
    cvx = next_obs[8] * 3.0
    cvy = next_obs[9] * 3.0
    crate_speed = (cvx * cvx + cvy * cvy) ** 0.5

    # 完成条件：完全进入 + 朝向 < 30° + 速度 < 0.05
    # cos(30°) ≈ 0.866 -> |sin| <= 0.5
    aligned_ok = 1.0 if abs(c_sin) <= 0.5 else 0.0
    slow_ok = 1.0 if crate_speed < 0.05 else 0.0
    done_cond = 1.0 if (inside > 0.5 and aligned_ok > 0.5 and slow_ok > 0.5) else 0.0

    if done_cond > 0.5:
        _STREAK[0] += 1
    else:
        _STREAK[0] = 0

    # ---------- 组件 ----------
    components = {}

    # 1) 主进度：货箱向泊位靠近的增量（只在更接近时给分）
    progress = d_now - d_nxt
    if progress < 0.0:
        progress = 0.0
    # 门控：对齐越好、越接近泊位，增量价值越高
    near_gate = 1.0 / (1.0 + 3.0 * d_nxt)
    gate = 0.3 + 0.7 * align
    components["crate_to_dock_progress"] = 600.0 * progress * near_gate * gate

    # 2) 轻柔接触：接触中且正在接近时惩罚
    crate_vx = next_obs[8] * 3.0
    crate_vy = next_obs[9] * 3.0
    crate_along_heading = crate_vx * next_obs[2] + crate_vy * next_obs[3]
    closing = obs[4] * 3.0 - crate_along_heading
    if closing < 0.0:
        closing = 0.0
    contact = 1.0 if next_obs[14] > 0.5 else 0.0
    gentleness = -1.2 * contact * closing
    components["soft_contact"] = gentleness

    # 3) 接近泊位时的速度抑制（仅在接近泊位时激活，且只在速度过快时惩罚）
    near_dock = 1.0 / (1.0 + 8.0 * d_nxt)
    over_speed = crate_speed - 0.05
    if over_speed < 0.0:
        over_speed = 0.0
    components["dock_speed_penalty"] = -3.0 * near_dock * over_speed

    # 4) 越界守卫：小车位置接近 ±1.0 时单调下降
    ax = abs(next_obs[0])
    ay = abs(next_obs[1])
    over_x = ax - 0.95
    if over_x < 0.0:
        over_x = 0.0
    over_y = ay - 0.95
    if over_y < 0.0:
        over_y = 0.0
    components["bounds_guard"] = -80.0 * (over_x * over_x + over_y * over_y) - 20.0 * (over_x + over_y)

    # 5) 障碍接近惩罚（前/左/右传感器）
    sf = next_obs[15]
    sl = next_obs[16]
    sr = next_obs[17]
    obs_pen = 0.0
    if sf > 0.85:
        obs_pen += (sf - 0.85)
    if sl > 0.9:
        obs_pen += (sl - 0.9)
    if sr > 0.9:
        obs_pen += (sr - 0.9)
    components["obstacle_penalty"] = -6.0 * obs_pen

    # 6) 一次性：首次进入泊位
    if inside > 0.5 and not _ENTERED[0]:
        _ENTERED[0] = True
        components["enter_dock_event"] = 30.0
    else:
        components["enter_dock_event"] = 0.0

    # 7) 一次性：完成事件（连续 10 步满足完成条件）
    success_event = 0.0
    if _STREAK[0] >= 10 and not _PAID[0]:
        _PAID[0] = True
        success_event = 300.0
    components["success_event"] = success_event

    # 8) 完成状态下其余组件必须恰好为 0
    if done_cond > 0.5:
        components["crate_to_dock_progress"] = 0.0
        components["soft_contact"] = 0.0
        components["dock_speed_penalty"] = 0.0
        components["obstacle_penalty"] = 0.0
        # 边界守卫保留（越界即失败，与完成状态不冲突；完成时小车在泊位附近，不会触发）
        if abs(components["bounds_guard"]) < 1e-9:
            components["bounds_guard"] = 0.0


    # ---- REPAIR: the one-off payoff, converted into a DENSE per-step stream ----
    # Paid on the candidate's own success predicate (done_cond: inside & aligned & slow),
    # the same +20/step that probe D's `dock_settled_hold` uses. Under the per-step clip of
    # 20 a one-off event can never be worth more than one step of such a stream.
    components["REPAIR_settled_stream"] = float(20.0 * done_cond)


    # ---- APPROACH (state form): dense reward for BEING near the dock ----
    # NOTE on scale: obs[12], obs[13] are normalised by FIELD_HALF_W/H (5.0 m, 4.0 m), and the
    # dock tolerance is 0.024 in those units, while the spawn distance is ~0.82. A proximity
    # term must therefore decay on a scale of ~0.05 units, not 1/30 -- the first version of this
    # file used 1/(1+30d) and the advantage probe showed it paying the DO-NOTHING controller
    # +0.73 per step (i.e. a near-constant bonus across the whole arena, not a proximity reward).
    _pd = (float(next_obs[12]) ** 2 + float(next_obs[13]) ** 2) ** 0.5
    components["APPROACH_proximity"] = float(20.0 * 2.718281828459045 ** (-_pd / 0.05))


    # ---- GENTLENESS: closing speed while in contact (the release-lead-time signal) ----
    _gcos_h, _gsin_h = obs[2], obs[3]
    _gcart_fwd = obs[4] * 3.0
    _galong = crate_vx * _gcos_h + crate_vy * _gsin_h
    _gclosing = _gcart_fwd - _galong
    if _gclosing < 0.0:
        _gclosing = 0.0
    components["REPAIR_gentleness"] = float(-0.05 * contact * _gclosing)

    total = 0.0
    for k in components:
        total += components[k]

    return float(total), components